version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules

  client:
    build: ./client
    ports:
      - '5173:5173'
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
